export const notificationRoleAccess = {
  GROUP_INVITE: "GROUP_INVITE",
  FOLLOW: "FOLLOW",
  COMMENT: "COMMENT",
  COMMUNITY_COMMENT: "COMMUNITY_COMMENT",
  REACTED_TO_POST: "REACTED_TO_POST",
  REACTED_TO_COMMUNITY_POST: "REACTED_TO_COMMUNITY_POST",
  REFETCHNOTIFICATIONS: "REFETCHNOTIFICATIONS",
};
